wx:
  mp:
    configs:
      - appId: wx738d5cd928816fa0
        secret: 4e262bf21fb03bc20a5140ed2a888f5f
        token: hcliu
        aesKey: LHznZTiUOlwohmxktYHFlFQJYnQMeCFPCw8J2QsUHGK

server:
  port: 80
  url:  http://f6e89853.natappfree.cc



spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
