wx:
  mp:
    configs:
      - appId: wx738d5cd928816fa0
        secret: 4e262bf21fb03bc20a5140ed2a888f5f
        token: hcliu
        aesKey: LHznZTiUOlwohmxktYHFlFQJYnQMeCFPCw8J2QsUHGK
server:
  port: 80



spring:
#  profiles:
#    active: dev
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
api:
  search:
    base-url: http://m.kkqws.com
    juzi-path: /v/api/getJuzi
    xiaoyu-path: /v/api/getXiaoyu
    search-path: /v/api/search
    searchx-path: /v/api/getSearchX
    token: i69
qinglong:
  url: http://47.103.2.139:5700
  client-id: RDPeU_1p6WlL
  client-secret: s5PP776sq_RhdPIy3y9nygMW
