wx:
  mp:
    configs:
      - appId: wx738d5cd928816fa0
        secret: 4e262bf21fb03bc20a5140ed2a888f5f
        token: hcliu
        aesKey: LHznZTiUOlwohmxktYHFlFQJYnQMeCFPCw8J2QsUHGK
server:
  port: 80
  url:  http://f6e89853.natappfree.cc:80  # 配置您的实际域名



spring:
#  profiles:
#    active: dev
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  redis:
    database: 0
    host: redis-14497.c52.us-east-1-4.ec2.redns.redis-cloud.com
    port: 14497
    username: default
    password: TL8Z6Eh6QHCD2QX1t0moAzCujC6W8xKL
api:
  search:
    base-url: http://m.kkqws.com
    uukk-base-url: http://uukk6.cn
    juzi-path: /v/api/getJuzi
    xiaoyu-path: /v/api/getXiaoyu
    search-path: /v/api/search
    searchx-path: /v/api/getSearchX
    token: i69
    ttzjb-path: /v/api/getTTZJB
    dyfx-path: /v/api/getDyfx
    juzi2-path: /v/api/getJuzi
    uukk-token: nd9pnq356a8
    uukk6-token: uukk6
    girls-path: /v/api/getGirls
    xiaoy-path: /v/api/getXiaoy
    ggang-path: /v/api/getGGang
    kkqws-token: i69
qinglong:
  url: http://47.103.2.139:5700
bark:
  key: qEnhyuDqQAcAtCKRCBWJ4e



